inherit_gem: { standard: config/base.yml }

plugins:
  - rubocop-capybara
  - rubocop-rails

AllCops:
  NewCops: disable
  SuggestExtensions: false

Rails/DynamicFindBy:
  Enabled: false
Rails/TimeZone:
  Exclude:
    - "spec/**/*"
